name = "Faithful 32x Auto-update"
author = "ColinLabDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e435a4fe2b2759b7ce6ffd56bb3d6aae03a60f1f0a79731e0b43634e468dc2"

[versions]
minecraft = "1.19"
