name = "Faithful 32x Auto-update"
author = "ColinLabDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "103c29f4e504cbf1950bedb14f569a6f998654dc1e0e763479d6dd7f376c5062"

[versions]
minecraft = "1.19"
