name = "Faithful-Java-32x"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3EF6A0B6E5AC8631D0B5FA0DCCFF0EE0720BC9542F02EBF96E25E00ED8E7B7D2"

[versions]
minecraft = "1.19"
