name = "Faithful-Java-32x"
version = "4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3EA51B9AC3442C8788312E2715379A0AC03389A09D43D726543BB4A2FF41FE2A"

[versions]
minecraft = "1.19"
