name = "Faithful-Java-32x"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5A2CDDB5E111C26E75C4425F2188A8B373C4BAA77D03D0263D8D4065D90736C0"

[versions]
minecraft = "1.19"
